version: '3.5'

services:
  app:
    build:
      dockerfile: ./docker/Dockerfile
      context: .
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://user:password@pg:5432/blog
      CONFIG_NAME: DevConfig
      LOGGER_LEVEL: INFO
    volumes:
    - ./blog:/app/blog
    - ./migrations:/app/migrations
    ports:
      - 5000:5000
    depends_on:
      - pg
  pg:
    image: postgres:13.1
    privileged: true
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
