"""add tag >-<- articles

Revision ID: 286b989725bf
Revises: 0a2b3c36e883
Create Date: 2023-01-25 19:12:15.282370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '286b989725bf'
down_revision = '0a2b3c36e883'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_tag_table',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article_model.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag_model.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_tag_table')
    # ### end Alembic commands ###
